### ISSUE TITLE
Icon load fail

### ISSUE THREAD

**Issue by toilatung** [Semantic-Org/UI-Icon#1]
Hi!
I using each element icon.css, grid.css (not using semantic-ui.css) and when loaded, icon don't show, just box icon and grid not correct 
![screen shot 2015-02-21 at 9 46 44 pm](https://cloud.githubusercontent.com/assets/9214596/6314479/2e280ce4-ba13-11e4-8b7f-fd13f8739935.png)

**Comment by jlukic** [comment]
Should be fixed
